#ifndef ONII_CORE_CONFIG_COMPILERS_ALTIUM_C_TO_HARDWARE_HPP
#define ONII_CORE_CONFIG_COMPILERS_ALTIUM_C_TO_HARDWARE_HPP

#if defined(__CHC__) 
# define ONII_COMPILER_ALTIUMCTOHARDWARE 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_ALTIUM_C_TO_HARDWARE_HPP
