#ifndef ONII_CORE_CONFIG_COMPILERS_CLANG_HPP
#define ONII_CORE_CONFIG_COMPILERS_CLANG_HPP

#if defined(__clang__) 
# define ONII_COMPILER_CLANG 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_CLANG_HPP
