#ifndef ONII_CORE_CONFIG_COMPILERS_COMEAU_HPP
#define ONII_CORE_CONFIG_COMPILERS_COMEAU_HPP

#if defined(__COMO__)
# define ONII_COMPILER_COMEAU 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_COMEAU_HPP
