#ifndef ONII_CORE_CONFIG_COMPILERS_CONVEX_HPP
#define ONII_CORE_CONFIG_COMPILERS_CONVEX_HPP

#if defined(__convexc__) 
# define ONII_COMPILER_CONVEXC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_CONVEX_HPP
