#ifndef ONII_CORE_CONFIG_COMPILERS_CRAY_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_CRAY_C_HPP

#if defined(_CRAYC) 
# define ONII_COMPILER_CRAYC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_CRAY_C_HPP
