#ifndef ONII_CORE_CONFIG_COMPILERS_DICE_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_DICE_C_HPP

#if defined(_DICE) 
# define ONII_COMPILER_DICEC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_DICE_C_HPP
