#ifndef ONII_CORE_CONFIG_COMPILERS_DIGITAL_MARS_HPP
#define ONII_CORE_CONFIG_COMPILERS_DIGITAL_MARS_HPP

#if defined(__DMC__) 
# define ONII_COMPILER_DMC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_DIGITAL_MARS_HPP
