#ifndef ONII_CORE_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP
#define ONII_CORE_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP

#if defined(__SYSC__) 
# define ONII_COMPILER_DIGNUSSYSTEMS 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP
