#ifndef ONII_CORE_CONFIG_COMPILERS_EDG_FRONTEND_HPP
#define ONII_CORE_CONFIG_COMPILERS_EDG_FRONTEND_HPP

#if defined(__EDG__) 
# define ONII_COMPILER_EDG 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_EDG_FRONTEND_HPP
