#ifndef ONII_CORE_CONFIG_COMPILERS_FUJITSU_HPP
#define ONII_CORE_CONFIG_COMPILERS_FUJITSU_HPP

#if defined(__FCC_VERSION)
# define ONII_COMPILER_FUJITSU 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_FUJITSU_HPP
