#ifndef ONII_CORE_CONFIG_COMPILERS_GREEN_HILL_HPP
#define ONII_CORE_CONFIG_COMPILERS_GREEN_HILL_HPP

#if defined(__ghs__) 
# define ONII_COMPILER_GREENHILL 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_GREEN_HILL_HPP
