#ifndef ONII_CORE_CONFIG_COMPILERS_HP_ACPP_HPP
#define ONII_CORE_CONFIG_COMPILERS_HP_ACPP_HPP

#if defined(__HP_aCC) 
# define ONII_COMPILER_HPACPP 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_HP_ACPP_HPP
