#ifndef ONII_CORE_CONFIG_COMPILERS_INTEL_HPP
#define ONII_CORE_CONFIG_COMPILERS_INTEL_HPP

#if defined(__INTEL_COMPILER) || defined(__ICC) || defined(__ECC) || defined(__ICL)
# define ONII_COMPILER_INTEL 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_INTEL_HPP
