#ifndef ONII_CORE_CONFIG_COMPILERS_METAWARE_HIGH_HPP
#define ONII_CORE_CONFIG_COMPILERS_METAWARE_HIGH_HPP

#if defined(__HIGHC__) 
# define ONII_COMPILER_HIGHC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_METAWARE_HIGH_HPP
