#ifndef ONII_CORE_CONFIG_COMPILERS_MICROSOFT_VISUAL_HPP
#define ONII_CORE_CONFIG_COMPILERS_MICROSOFT_VISUAL_HPP

#if defined(_MSC_VER) 
# define ONII_COMPILER_VISUAL 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MICROSOFT_VISUAL_HPP
