#ifndef ONII_CORE_CONFIG_COMPILERS_MICROTEC_HPP
#define ONII_CORE_CONFIG_COMPILERS_MICROTEC_HPP

#if defined(_MRI) 
# define ONII_COMPILER_MRI 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MICROTEC_HPP
