#ifndef ONII_CORE_CONFIG_COMPILERS_MICROWAY_NDP_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_MICROWAY_NDP_C_HPP

#if defined(__NDPC__) || defined(__NDPX__)
# define ONII_COMPILER_NDPC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MICROWAY_NDP_C_HPP
