#ifndef ONII_CORE_CONFIG_COMPILERS_MINGW_HPP
#define ONII_CORE_CONFIG_COMPILERS_MINGW_HPP

#if defined(__MINGW32__) 
# define ONII_COMPILER_MINGW32 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MINGW_HPP
