#ifndef ONII_CORE_CONFIG_COMPILERS_MIPSPRO_HPP
#define ONII_CORE_CONFIG_COMPILERS_MIPSPRO_HPP

#if defined(__sgi) || defined(sgi)
# define ONII_COMPILER_MIPS 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MIPSPRO_HPP
