#ifndef ONII_CORE_CONFIG_COMPILERS_MIRACLE_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_MIRACLE_C_HPP

#if defined(MIRACLE) 
# define ONII_COMPILER_MIRACLEC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_MIRACLE_C_HPP
