#ifndef ONII_CORE_CONFIG_COMPILERS_NORCROFT_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_NORCROFT_C_HPP

#if defined(__CC_NORCROFT) 
# define ONII_COMPILER_NORCROFTC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_NORCROFT_C_HPP
