#ifndef ONII_CORE_CONFIG_COMPILERS_OPEN64_HPP
#define ONII_CORE_CONFIG_COMPILERS_OPEN64_HPP

#if defined(__OPEN64__) || defined(__OPENCC__)
# define ONII_COMPILER_OPEN64 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_OPEN64_HPP
