#ifndef ONII_CORE_CONFIG_COMPILERS_PELLES_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_PELLES_C_HPP

#if defined(__POCC__) 
# define ONII_COMPILER_PELLESC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_PELLES_C_HPP
