#ifndef ONII_CORE_CONFIG_COMPILERS_RENESAS_HPP
#define ONII_CORE_CONFIG_COMPILERS_RENESAS_HPP

#if defined(__RENESAS__) || defined(__HITACHI__)
# define ONII_COMPILER_RENESAS 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_RENESAS_HPP
