#ifndef ONII_CORE_CONFIG_COMPILERS_SASC_HPP
#define ONII_CORE_CONFIG_COMPILERS_SASC_HPP

#if defined(SASC) || defined(__SASC) || defined(__SASC__)
# define ONII_COMPILER_SASC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_SASC_HPP
