#ifndef ONII_CORE_CONFIG_COMPILERS_SCO_OPENSERVER_HPP
#define ONII_CORE_CONFIG_COMPILERS_SCO_OPENSERVER_HPP

#if defined(_SCO_DS) 
# define ONII_COMPILER_SCO 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_SCO_OPENSERVER_HPP
