#ifndef ONII_CORE_CONFIG_COMPILERS_SMALL_DEVICE_C_COMPILER_HPP
#define ONII_CORE_CONFIG_COMPILERS_SMALL_DEVICE_C_COMPILER_HPP

#if defined(SDCC) 
# define ONII_COMPILER_SDCC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_SMALL_DEVICE_C_COMPILER_HPP
