#ifndef ONII_CORE_CONFIG_COMPILERS_SN_COMPILER_HPP
#define ONII_CORE_CONFIG_COMPILERS_SN_COMPILER_HPP

#if defined(__SNC__) 
# define ONII_COMPILER_SNC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_SN_COMPILER_HPP
