#ifndef ONII_CORE_CONFIG_COMPILERS_SYMANTEC_HPP
#define ONII_CORE_CONFIG_COMPILERS_SYMANTEC_HPP

#if defined(__SC__) 
# define ONII_COMPILER_SYMANTEC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_SYMANTEC_HPP
