#ifndef ONII_CORE_CONFIG_COMPILERS_TENDRA_HPP
#define ONII_CORE_CONFIG_COMPILERS_TENDRA_HPP

#if defined(__TenDRA__) 
# define ONII_COMPILER_TENDRA 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_TENDRA_HPP
