#ifndef ONII_CORE_CONFIG_COMPILERS_TINY_C_HPP
#define ONII_CORE_CONFIG_COMPILERS_TINY_C_HPP

#if defined(__TINYC__) 
# define ONII_COMPILER_TINYC 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_TINY_C_HPP
