#ifndef ONII_CORE_CONFIG_COMPILERS_TURBO_HPP
#define ONII_CORE_CONFIG_COMPILERS_TURBO_HPP

#if defined(__TURBOC__) 
# define ONII_COMPILER_TURBO 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_TURBO_HPP
