#ifndef ONII_CORE_CONFIG_COMPILERS_ULTIMATE_HPP
#define ONII_CORE_CONFIG_COMPILERS_ULTIMATE_HPP

#if defined(_UCC)
# define ONII_COMPILER_ULTIMATE 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_ULTIMATE_HPP
