#ifndef ONII_CORE_CONFIG_COMPILERS_WATCOM_HPP
#define ONII_CORE_CONFIG_COMPILERS_WATCOM_HPP

#if defined(__WATCOMC__) 
# define ONII_COMPILER_WATCOM 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_WATCOM_HPP
