#ifndef ONII_CORE_CONFIG_COMPILERS_ZORTECH_HPP
#define ONII_CORE_CONFIG_COMPILERS_ZORTECH_HPP

#if defined(__ZTC__) 
# define ONII_COMPILER_ZORTECH 1
#endif

#endif // ONII_CORE_CONFIG_COMPILERS_ZORTECH_HPP
