#ifndef ONII_CORE_CONFIG_ARCHITECTURES_ALPHA_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_ALPHA_HPP

#if defined(__alpha__) || defined(__alpha) || defined(_M_ALPHA)
# define ONII_ARCH_ALPHA 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_ALPHA_HPP
