#ifndef ONII_CORE_CONFIG_ARCHITECTURES_ARM64_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_ARM64_HPP

#if defined(__aarch64__)
# define ONII_ARCH_ARM64 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_ARM64_HPP
