#ifndef ONII_CORE_CONFIG_ARCHITECTURES_BLACKFIN_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_BLACKFIN_HPP

#if defined(__bfin) || defined(__BFIN__)
# define ONII_ARCH_BLACKFIN 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_BLACKFIN_HPP
