#ifndef ONII_CORE_CONFIG_ARCHITECTURES_CONVEX_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_CONVEX_HPP

#if defined(__convex__)
# define ONII_ARCH_CONVEX 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_CONVEX_HPP
