#ifndef ONII_CORE_CONFIG_ARCHITECTURES_MOTOROLA_68K_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_MOTOROLA_68K_HPP

#if defined(__m68k__) || defined(M68000) || defined(__MC68K__)
# define ONII_ARCH_M68K 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_MOTOROLA_68K_HPP
