#ifndef ONII_CORE_CONFIG_ARCHITECTURES_SPARC_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_SPARC_HPP

#if defined(__sparc__) || defined(__sparc)
# define ONII_ARCH_SPARC 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_SPARC_HPP
