#ifndef ONII_CORE_CONFIG_ARCHITECTURES_SUPERH_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_SUPERH_HPP

#if defined(__sh__)
# define ONII_ARCH_SUPERH 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_SUPERH_HPP
