#ifndef ONII_CORE_CONFIG_ARCHITECTURES_TMS470_HPP
#define ONII_CORE_CONFIG_ARCHITECTURES_TMS470_HPP

#if defined(__TMS470__)
# define ONII_ARCH_TMS470 1
#endif

#endif // ONII_CORE_CONFIG_ARCHITECTURES_TMS470_HPP
