#ifndef ONII_CONFIG_ARCHITECTURES_EPIPHANY_HPP
#define ONII_CONFIG_ARCHITECTURES_EPIPHANY_HPP

#if defined(__epiphany__)
# define ONII_ARCH_EPIPHANY 1
#endif

#endif // ONII_CONFIG_ARCHITECTURES_EPIPHANY_HPP
