#ifndef ONII_CONFIG_ARCHITECTURES_PYRAMID_9810_HPP
#define ONII_CONFIG_ARCHITECTURES_PYRAMID_9810_HPP

#if defined(pyr)
# define ONII_ARCH_PYRAMID 1
#endif

#endif // ONII_CONFIG_ARCHITECTURES_PYRAMID_9810_HPP
