#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_ANDROID_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_ANDROID_HPP

#if defined(__ANDROID__) 
# define ONII_OS_ANDROID 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_ANDROID_HPP
