#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_DOMAINOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_DOMAINOS_HPP

#if defined(apollo) 
# define ONII_OS_APOLLODOMAINOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_DOMAINOS_HPP
