#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_AEGIS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_AEGIS_HPP

#if defined(aegis)
# define ONII_OS_APOLLOAEGIS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_APOLLO_AEGIS_HPP
