#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_BADA_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_BADA_HPP

#if defined(__nucleus__) 
# define ONII_OS_BADA 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_BADA_HPP
