#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_BEOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_BEOS_HPP

#if defined(__BEOS__) 
# define ONII_OS_BEOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_BEOS_HPP
