#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_BLUE_GENE_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_BLUE_GENE_HPP

#if defined(__bg__) 
# define ONII_OS_BLUEGENE 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_BLUE_GENE_HPP
