#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_BSDOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_BSDOS_HPP

#if defined(__bsdi__) 
# define ONII_OS_BSDOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_BSDOS_HPP
