#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_DYNIXPTX_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_DYNIXPTX_HPP

#if defined(_SEQUENT_) || defined(sequent)
# define ONII_OS_DYNIXPTX 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_DYNIXPTX_HPP
