#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_ECOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_ECOS_HPP

#if defined(__ECOS) 
# define ONII_OS_ECOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_ECOS_HPP
