#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_IBM_OS400_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_IBM_OS400_HPP

#if defined(__OS400__) 
# define ONII_OS_IBMOS400 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_IBM_OS400_HPP
