#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_MORPHOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_MORPHOS_HPP

#if defined(__MORPHOS__)
# define ONII_OS_MORPHOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_MORPHOS_HPP
