#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_NETBSD_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_NETBSD_HPP

#if defined(__NetBSD__) 
# define ONII_OS_NETBSD 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_NETBSD_HPP
