#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_NONSTOP_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_NONSTOP_HPP

#if defined(__TANDEM) 
# define ONII_OS_NONSTOP 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_NONSTOP_HPP
