#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_PALM_OS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_PALM_OS_HPP

#if defined(__palmos__)
# define ONII_OS_PALM 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_PALM_OS_HPP
