#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_QNX_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_QNX_HPP

#if defined(__QNX__) || defined(__QNXNTO__)
# define ONII_OS_QNX 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_QNX_HPP
