#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_SOLARIS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_SOLARIS_HPP

#if defined(sun) || defined(__sun)
# define ONII_OS_SOLARIS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_SOLARIS_HPP
