#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_STRATUS_VOS_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_STRATUS_VOS_HPP

#if defined(__VOS__) 
# define ONII_OS_STRATUSVOS 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_STRATUS_VOS_HPP
