#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_SYLLABLE_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_SYLLABLE_HPP

#if defined(__SYLLABLE__) 
# define ONII_OS_SYLLABLE 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_SYLLABLE_HPP
