#ifndef ONII_CORE_CONFIG_OPERATING_SYSTEMS_UNIXWARE_HPP
#define ONII_CORE_CONFIG_OPERATING_SYSTEMS_UNIXWARE_HPP

#if defined(sco) || defined(_UNIXWARE7)
# define ONII_OS_UNIXWARE 1
#endif

#endif // ONII_CORE_CONFIG_OPERATING_SYSTEMS_UNIXWARE_HPP
