#ifndef ONII_CONFIG_OPERATING_SYSTEMS_AMDAHL_UTS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_AMDAHL_UTS_HPP

#if defined(UTS)
# define ONII_OS_AMDAHLUTS 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_AMDAHL_UTS_HPP
