#ifndef ONII_CONFIG_OPERATING_SYSTEMS_AMIGAOS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_AMIGAOS_HPP

#if defined(AMIGA) || defined(__amigaos__)
# define ONII_OS_AMIGA 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_AMIGAOS_HPP
