#ifndef ONII_CONFIG_OPERATING_SYSTEMS_CONVEXOS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_CONVEXOS_HPP

#if defined(__convex__)
# define ONII_OS_CONVEX 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_CONVEXOS_HPP
