#ifndef ONII_CONFIG_OPERATING_SYSTEMS_DRAGONFLY_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_DRAGONFLY_HPP

#if defined(__DragonFly__)
# define ONII_OS_DRAGONFLY 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_DRAGONFLY_HPP
