#ifndef ONII_CONFIG_OPERATING_SYSTEMS_FREEBSD_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_FREEBSD_HPP

#if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
# define ONII_OS_FREEBSD 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_FREEBSD_HPP
