#ifndef ONII_CONFIG_OPERATING_SYSTEMS_HIUX_MPP_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_HIUX_MPP_HPP

#if defined(__hiuxmpp)
# define ONII_OS_HIUXMPP 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_HIUX_MPP_HPP
