#ifndef ONII_CONFIG_OPERATING_SYSTEMS_INTEGRITY_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_INTEGRITY_HPP

#if defined(__INTEGRITY)
# define ONII_OS_INTEGRITY 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_INTEGRITY_HPP
