#ifndef ONII_CONFIG_OPERATING_SYSTEMS_IRIX_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_IRIX_HPP

#if defined(sgi) || defined(__sgi)
# define ONII_OS_IRIX 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_IRIX_HPP
