#ifndef ONII_CONFIG_OPERATING_SYSTEMS_KFREEBSD_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_KFREEBSD_HPP

#if (defined(__FreeBSD_kernel__) && defined(__GLIBC__))
# define ONII_OS_KFREEBSD 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_KFREEBSD_HPP
