#ifndef ONII_CONFIG_OPERATING_SYSTEMS_LYNXOS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_LYNXOS_HPP

#if defined(__Lynx__)
# define ONII_OS_LYNX 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_LYNXOS_HPP
