#ifndef ONII_CONFIG_OPERATING_SYSTEMS_MICROWARE_OS9_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_MICROWARE_OS9_HPP

#if defined(__OS9000) || defined(_OSK)
# define ONII_OS_MICROWAREOS9 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_MICROWARE_OS9_HPP
