#ifndef ONII_CONFIG_OPERATING_SYSTEMS_MINIX_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_MINIX_HPP

#if defined(__minix)
# define ONII_OS_MINIX 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_MINIX_HPP
