#ifndef ONII_CONFIG_OPERATING_SYSTEMS_MPEIX_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_MPEIX_HPP

#if defined(mpeix) || defined(__mpexl)
# define ONII_OS_MPEIX 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_MPEIX_HPP
