#ifndef ONII_CONFIG_OPERATING_SYSTEMS_NUCLEUS_RTOS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_NUCLEUS_RTOS_HPP

#if defined(__nucleus__)
# define ONII_OS_NUCLEUS 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_NUCLEUS_RTOS_HPP
