#ifndef ONII_CONFIG_OPERATING_SYSTEMS_OPENBSD_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_OPENBSD_HPP

#if defined(__OpenBSD__)
# define ONII_OS_OPENBSD 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_OPENBSD_HPP
