#ifndef ONII_CONFIG_OPERATING_SYSTEMS_PYRAMID_DCOSX_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_PYRAMID_DCOSX_HPP

#if defined(pyr)
# define ONII_OS_PYRAMID 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_PYRAMID_DCOSX_HPP
