#ifndef ONII_CONFIG_OPERATING_SYSTEMS_RELIANT_UNIX_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_RELIANT_UNIX_HPP

#if defined(sinux)
# define ONII_OS_RELIANT 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_RELIANT_UNIX_HPP
