#ifndef ONII_CONFIG_OPERATING_SYSTEMS_SCO_OPENSERVER_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_SCO_OPENSERVER_HPP

#if defined(M_I386) || defined(M_XENIX) || defined(_SCO_DS)
# define ONII_OS_SCOOPENSERVER 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_SCO_OPENSERVER_HPP
