#ifndef ONII_CONFIG_OPERATING_SYSTEMS_SYMBIAN_OS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_SYMBIAN_OS_HPP

#if defined(__SYMBIAN32__)
# define ONII_OS_SYMBIAN 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_SYMBIAN_OS_HPP
