#ifndef ONII_CONFIG_OPERATING_SYSTEMS_UNICOS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_UNICOS_HPP

#if defined(_UNICOS)
# define ONII_OS_UNICOS 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_UNICOS_HPP
