#ifndef ONII_CONFIG_OPERATING_SYSTEMS_UNICOSMP_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_UNICOSMP_HPP

#if defined(_CRAY) || defined(__crayx1)
# define ONII_OS_UNICOSMP 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_UNICOSMP_HPP
