#ifndef ONII_CONFIG_OPERATING_SYSTEMS_VMS_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_VMS_HPP

#if defined(VMS) || defined(__VMS)
# define ONII_OS_VMS 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_VMS_HPP
