#ifndef ONII_CONFIG_OPERATING_SYSTEMS_WINDOWSCE_HPP
#define ONII_CONFIG_OPERATING_SYSTEMS_WINDOWSCE_HPP

#if defined(_WIN32_WCE)
# define ONII_OS_WINDOWSCE 1
#endif

#endif // ONII_CONFIG_OPERATING_SYSTEMS_WINDOWSCE_HPP
