#ifndef ONII_CORE_CONFIG_ENVIRONMENTS_CYGWIN_HPP
#define ONII_CORE_CONFIG_ENVIRONMENTS_CYGWIN_HPP

#if defined(__CYGWIN__) 
# define ONII_ENV_CYGWIN 1
#endif

#endif // ONII_CORE_CONFIG_ENVIRONMENTS_CYGWIN_HPP
