#ifndef ONII_CORE_CONFIG_ENVIRONMENTS_INTERIX_HPP
#define ONII_CORE_CONFIG_ENVIRONMENTS_INTERIX_HPP

#if defined(__INTERIX) 
# define ONII_ENV_INTERIX 1
#endif

#endif // ONII_CORE_CONFIG_ENVIRONMENTS_INTERIX_HPP
