#ifndef ONII_CORE_CONFIG_ENVIRONMENTS_UNIX_HPP
#define ONII_CORE_CONFIG_ENVIRONMENTS_UNIX_HPP

#if defined(__unix__) || defined(__unix)
# define ONII_ENV_UNIX 1
#endif

#endif // ONII_CORE_CONFIG_ENVIRONMENTS_UNIX_HPP
