#ifndef ONII_CORE_CONFIG_ENVIRONMENTS_WINDU_HPP
#define ONII_CORE_CONFIG_ENVIRONMENTS_WINDU_HPP

#if defined(_WINDU_SOURCE)
# define ONII_ENV_WINDU 1
#endif

#endif // ONII_CORE_CONFIG_ENVIRONMENTS_WINDU_HPP
