#ifndef ONII_CONFIG_LIBRARIES_MICROSOFT_FOUNDATION_CLASSES_HPP
#define ONII_CONFIG_LIBRARIES_MICROSOFT_FOUNDATION_CLASSES_HPP

#if defined(_MFC_VER)
# define ONII_LIB_MFC 1
#endif

#endif // ONII_CONFIG_LIBRARIES_MICROSOFT_FOUNDATION_CLASSES_HPP
