#ifndef ONII_CONFIG_COMPILERS_ALTIUM_MICROBLAZE_C_HPP
#define ONII_CONFIG_COMPILERS_ALTIUM_MICROBLAZE_C_HPP

#if defined(__CMB__)
# define ONII_COMPILER_ALTIUMMICROBLAZEC 1
#endif

#endif // ONII_CONFIG_COMPILERS_ALTIUM_MICROBLAZE_C_HPP
