#ifndef ONII_CONFIG_COMPILERS_AMSTERDAM_COMPILER_KIT_HPP
#define ONII_CONFIG_COMPILERS_AMSTERDAM_COMPILER_KIT_HPP

#if defined(__ACK__)
# define ONII_COMPILER_AMSTERDAMKIT 1
#endif

#endif // ONII_CONFIG_COMPILERS_AMSTERDAM_COMPILER_KIT_HPP
