#ifndef ONII_CONFIG_COMPILERS_ARM_COMPILER_HPP
#define ONII_CONFIG_COMPILERS_ARM_COMPILER_HPP

#if defined(__CC_ARM)
# define ONII_COMPILER_ARM 1
#endif

#endif // ONII_CONFIG_COMPILERS_ARM_COMPILER_HPP
