#ifndef ONII_CONFIG_COMPILERS_BORLAND_HPP
#define ONII_CONFIG_COMPILERS_BORLAND_HPP

#if defined(__BORLANDC__) || defined(__CODEGEARC__)
# define ONII_COMPILER_BORLAND 1
#endif

#endif // ONII_CONFIG_COMPILERS_BORLAND_HPP
