#ifndef ONII_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP
#define ONII_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP

#if defined(__SYSC__)
# define ONII_COMPILER_DIGNUSSYSTEMS 1
#endif

#endif // ONII_CONFIG_COMPILERS_DIGNUS_SYSTEMS_HPP
