#ifndef ONII_CONFIG_COMPILERS_DJGPP_HPP
#define ONII_CONFIG_COMPILERS_DJGPP_HPP

#if defined(__DJGPP__) || defined(__GO32__)
# define ONII_COMPILER_DJGPP 1
#endif

#endif // ONII_CONFIG_COMPILERS_DJGPP_HPP
