#ifndef ONII_CONFIG_COMPILERS_IMAGECRAFT_C_HPP
#define ONII_CONFIG_COMPILERS_IMAGECRAFT_C_HPP

#if defined(__IMAGECRAFT__)
# define ONII_COMPILER_IMAGECRAFT 1
#endif

#endif // ONII_CONFIG_COMPILERS_IMAGECRAFT_C_HPP
