#ifndef ONII_CONFIG_COMPILERS_METROWERKS_CODEWARRIOR_HPP
#define ONII_CONFIG_COMPILERS_METROWERKS_CODEWARRIOR_HPP

#if defined(__MWERKS__) || defined(__CWCC__)
# define ONII_COMPILER_MWERKS 1
#endif

#endif // ONII_CONFIG_COMPILERS_METROWERKS_CODEWARRIOR_HPP
