#ifndef ONII_CONFIG_COMPILERS_MINGW_W64_HPP
#define ONII_CONFIG_COMPILERS_MINGW_W64_HPP

#if defined(__MINGW64__)
# define ONII_COMPILER_MINGW64 1
#endif

#endif // ONII_CONFIG_COMPILERS_MINGW_W64_HPP
