#ifndef ONII_CONFIG_COMPILERS_PACIFIC_C_HPP
#define ONII_CONFIG_COMPILERS_PACIFIC_C_HPP

#if defined(__PACIFIC__)
# define ONII_COMPILER_PACIFICC 1
#endif

#endif // ONII_CONFIG_COMPILERS_PACIFIC_C_HPP
