#ifndef ONII_CONFIG_COMPILERS_PORTLAND_GROUP_HPP
#define ONII_CONFIG_COMPILERS_PORTLAND_GROUP_HPP

#if defined(__PGI)
# define ONII_COMPILER_PORTLANDGRP 1
#endif

#endif // ONII_CONFIG_COMPILERS_PORTLAND_GROUP_HPP
