#ifndef ONII_CONFIG_COMPILERS_STRATUS_VOS_C_HPP
#define ONII_CONFIG_COMPILERS_STRATUS_VOS_C_HPP

#if defined(__VOSC__)
# define ONII_COMPILER_VOSC 1
#endif

#endif // ONII_CONFIG_COMPILERS_STRATUS_VOS_C_HPP
