#ifndef ONII_CONFIG_COMPILERS_SUN_STUDIO_HPP
#define ONII_CONFIG_COMPILERS_SUN_STUDIO_HPP

#if defined(__SUNPRO_C) || defined(__SUNPRO_CC)
# define ONII_COMPILER_SUNSTUDIO 1
#endif

#endif // ONII_CONFIG_COMPILERS_SUN_STUDIO_HPP
