#ifndef ONII_CONFIG_COMPILERS_THINK_C_HPP
#define ONII_CONFIG_COMPILERS_THINK_C_HPP

#if defined(THINKC3) || defined(THINKC4)
# define ONII_COMPILER_THINKC 1
#endif

#endif // ONII_CONFIG_COMPILERS_THINK_C_HPP
